.eslintignore, .eslintrc.json, .husky/pre-commit, .prettierignore, .prettierrc, jest.config.ts, next.config.mjs, package-lock.json, package.json, postcss.config.mjs, src/app/layout.tsx, src/app/page.tsx, src/app/providers/Providers.tsx, tailwind.config.ts, tsconfig.json
- `from`: joshuayeyo/moguaFE: chore/2/initial-setting
- `to`: main
X
- #2 
@ITHPARK @wjsdncl @Stilllee @seoyeon1123
#1, #2 만 `main` 브랜치에 에 직접 올리겠습니다.
=> Chore(#2): 프로젝트 초기 설정

src/app/page.tsx, src/components/common/Dropdown.tsx, src/components/common/Popover.tsx, src/styles/globals.css
- `from`: Feat/8/add-dropdown
- Popover 제작
- Dropdown 제작
- 드롭다운 global CSS 추가
X
- #8 
@joshuayeyo @ITHPARK @Stilllee @seoyeon1123
=> Feat(#8): 드롭다운 컴포넌트 제작

src/app/layout.tsx, src/app/page.tsx
- `from`: feat/18/layout
- Navigation Bar 컴포넌트 적용시 메인의 마지막 요소가 가려지지 않게 root layout의 구조를 변경 했습니다.
https://github.com/user-attachments/assets/679b8677-6bec-4fca-9e99-f3666df35959
- #18 
=> Feat(#18): 네비게이션 바 적용을 위한 레이아웃 설정

src/app/page.tsx, src/components/common/buttons/ETCButton.tsx, src/components/common/buttons/IconButton.tsx, src/components/common/buttons/OutlinePrimaryButton.tsx, src/components/common/buttons/OutlineSecondaryButton.tsx, src/components/common/buttons/SolidButton.tsx, src/styles/globals.css, src/types/button.ts
- `from`: feat/8/button
1. 디자인 시안에 정의된 버튼 컴포넌트들을 각각 구현
- `SolidButton` (Primary/Secondary)
- `OutlinePrimaryButton`
- `OutlineSecondaryButton`
-  `IconButton`
-  `ETCButton`
2. 공통 스타일 처리
- 중복되는 스타일은 `btn-base` 클래스로 관리
- `size`별 공통 스타일은 `btn-size-{size}` 클래스로 관리
3. props 및 type 특징
- 각 버튼 컴포넌트는 `ButtonHTMLAttributes<HTMLButtonElement>`를 확장하여 기본 button의 속성을 모두 사용할 수 있습니다. 
- `onClick`, `type`, `disabled` 등 HTML button 속성을 그대로 사용 가능
- `state`: state prop으로 `'default' | 'activated' | 'inactive'` 처리. `state="inactive"`일 경우 자동으로 `disabled` 처리가 됩니다.
- `size` : 버튼 사이즈
- `children`: 자식요소
- `className`: 필요시 외부에서 추가 스타일 지정 가능
- `hierarchy`: SolidButton 한정 종류(primary/secondary)를 결정합니다.
4. 참고 사항
- 버튼마다 받는 props의 종류와 개수가 상이하니 각 컴포넌트의 props type과 기본값을 잘 …
=> Feat(#8): 공용 버튼 컴포넌트 제작

.github/pull_request_template.md, .github/workflows/CI.yml
- `from`: feat/1/ci-yml
- 리뷰 요구 인원 수 변경 `4 => 3`
#1 
=> Docs(#1): 인원 변경에 따른 파일 수정

src/components/common/nav-bar/NavBar.tsx
- `from`: fix/28/nav-bar
- 태블릿 뷰에서 양쪽 padding값 수정
- #28 
=> Refector(#28): 네비게이션 바 태블릿 디자인 수정

src/styles/globals.css
- `from`: fix/43/review
- 리뷰카드 컴포넌트에 적용될 css 클래스 이름을 잘못 적어 생긴 오류를 수정하였습니다. (md => desktop)
<details>
<summary>오류 및 수정된 css</summary>
</details>
x
- #43 
@joshuayeyo @wjsdncl @Stilllee
=> Fix(#43): 반응형 css 클래스 수정

.github/workflows/CI.yml
- `from`: fix/45/edit-ci-yml
- 머지 동작을 build와 분리하였습니다.
#45 
=> Fix(#45): merge 동작 관련 코드 수정

.github/workflows/CI_DEVELOP_PR-.yml, .github/workflows/CI_DEVELOP_PUSH.yml, .github/workflows/CI_MAIN_PR.yml
- `from`: feat/52/add-more-ci
- CI.yml 파일 이름 변경
- main 브랜치 병합 CI 워크플로우 추가 (성공시 병합 자동화)
- Develop 브랜치 병합 후 CI 워크플로우 추가
#52 ### 리뷰어 멘션하기
=> Feat(#52): CI 파일 추가

.github/workflows/CI_DEVELOP_PR-.yml
- `from`: fix/54/mod-ci-file
- 중간에 Review 수를 체크하는 로직을 추가했습니다. (어렵네요..)
#54 ### 리뷰어 멘션하기
=> Fix(#54): workflow 자동 머지 이슈 해결

src/app/layout.tsx, src/app/page.tsx, src/components/common/Calendar.tsx, src/components/common/modals/CalendarModal.tsx, src/components/common/modals/CityModal.tsx, src/components/common/modals/FilterModal.tsx, src/components/common/modals/StateModal.tsx, src/hooks/useCalendar.ts, tailwind.config.ts
- `from`: feat/47/modals
- 기존 모달은 초기 데이터를 안 받아서 전에 선택한 데이트를 확인 할 수 없어서 초기 데이터를 받을 수 있도로 개선했습니다.
X
- close #47 
=> Refactor(#47): 날짜, 지역, 상태 모달 외부에서 초기 데이터 받아오도록 개선

src/app/providers/Providers.tsx
- `from`: refactor/59/query
- 탠스택쿼리 프로바이더를 `app router` [권장설정](https://tanstack.com/query/latest/docs/framework/react/guides/advanced-ssr#initial-setup) 으로 수정했습니다.
X
X
- close #59 
=> Refactor(#59): TQ Provider 설정 변경

src/components/common/Header.tsx
- `from`: feat/63/header
- Header 컴포넌트에 z-index 속성을 추가하여 모달을 제외한 요소 최상단에 위치하게 수정하였습니다. 
- #63 
@joshuayeyo @wjsdncl @Stilllee
=> Feat(#63): Header 컴포넌트 z-index 속성 추가

src/app/layout.tsx
- `from`: style/67/layout
- 좌우 padding 추가
#67 
=> Style(#67): mobile, tablet 좌우 padding 추가

package-lock.json, package.json, src/app/(example)/input/page.tsx, src/components/common/inputs/SelectBox.tsx, src/components/common/inputs/TextArea.tsx, src/components/common/inputs/TextInput.tsx, src/hooks/inputs/style.ts
- `from`: feat/2/common-textArea
- 공통 TextArea 추가
- 공통 TextInput required label CSS 수정
- 공통 TextInput 이중패딩 수정
- ### 결과 이미지(화면 캡쳐해서)
#2 
- @ITHPARK @wjsdncl @Stilllee
=> Feat(#2): 공통 Text Area 추가

src/hooks/inputs/images/useIndexedDB.ts, src/hooks/inputs/images/useUploadImage.ts
- `from`: fix/75/indexedDB
- 초기 `images`스토어 생성 문제 해결
#75 
=> Fix(#75): indexedDB 초기 objectStore 생성 문제 해결

src/data/mockCardData.ts
- `from`: fix/86/card
- 모임 카드 mock데이터 유저 프로필 정보 타입 수정으로 버그 픽스 `userProfile => profileImageUrl`
- #86 
@joshuayeyo  @wjsdncl @Stilllee
=> Fix(#86): mock 데이터 타입오류 수정

src/app/(example)/input/page.tsx, src/app/layout.tsx, src/hoc/withAuth.tsx, src/hooks/auths/InitializeUser.ts, src/hooks/auths/useRedirectIfUnsigned.ts, src/hooks/auths/useSignIn.ts, src/hooks/auths/useTokenState.ts, src/store/auth/useUserStore.ts
- `from`: feat/14/sign-in-page
- Sign-in 토큰 처리 훅 추가
- useUserStore 추가
- Cookie 핸들링하는 커스텀 훅 추가
- 비로그인 상태에서 로그인 페이지로 강제 리다이렉트시키는 훅 추가
#14 
- 본인 username 제외하고 PR 날려주세요 
@ITHPARK @wjsdncl @Stillle
=> Feat(#14): 로그인 관련 커스텀 훅 추가

src/hooks/auths/useTokenState.ts
- `from`: fix/91/usetokenState-hook
- 클라이언트 사이드에서만 동작하도록 변경
#91 
=> Fix(#91): useTokenState 클라이언트 사이드에서만 작동하도록 변경

src/app/(auth)/sign-up/page.tsx, src/app/(auth)/sign-up/success/page.tsx, src/components/auth/AuthInputs.tsx
- `from`: style/14/sign-up-page
- /sign-up 페이지 CSS
- /sign-up/success 페이지 CSS
- /sign-up
- /sign-up/success
#14 
=> Style(#14): 회원가입 페이지 CSS

src/app/layout.tsx, src/components/common/nav-bar/NavBar.tsx
- `from`: feat/96/nav-bar
- 스토어에서 불러온 유저id를 '마이페이지' 네비게이션 경로에 적용했습니다.
- #96 
=> Feat(#96)네비게이션 바 유저정보 연결

src/app/user/[id]/page.tsx, src/components/user-page/MeetingList.tsx, src/components/user-page/UserTabs.tsx, src/hooks/useInfiniteMeetings.ts, src/types/user-page/index.ts, src/utils/userContentMapper.ts, src/utils/userPage.ts
- `from`: feat/13/user-page
- 환경변수로 관리하던 토큰을 제거하고 실제 로그인한 유저의 토큰으로 교체했습니다.
- #13 
``
=> Feat(#13): 유저페이지 로그인 토큰 적용

src/components/common/review/ReviewContent.tsx, src/components/user-page/EmptyState.tsx, src/components/user-page/MeetingList.tsx, src/types/user-page/index.ts
- `from`: feat/issue번호/기능명
- 모임 개설하기 버튼에 경로 추가
- 내 페이지에서만 모임 개설하기 버튼 노출
https://github.com/user-attachments/assets/14719b53-7760-41f7-9d63-27a188dc53ef
- #13 
@joshuayeyo @ITHPARK
=> Feat(#13): 유저페이지에 모임생성 페이지 이동 연결

src/components/common/Header.tsx, src/components/edit-profile/AccountActionButtons.tsx
- `from`: feat/issue번호/기능명
- 헤더 컴포넌트에 프로필수정페이지 경로 연결
- 로그아웃 기능 연결
https://github.com/user-attachments/assets/c85e8268-e029-48f3-8829-32d303f38558
- #111 
@joshuayeyo @ITHPARK
=> Feat(#111): 프로필 수정 페이지 경로이동 및 로그아웃 연결

src/components/create/CreateForm.tsx, src/lib/main/meetup.api.ts, src/utils/cookie.ts
- `from`: fix/107/meetup-post
- 모임 생성 시 쿠키에서 토큰을 훅을 이용해서 못받아오는 문제를 `getAccessToken` 유틸 함수를 만들어서 해결했습니다.
- close #107 
=> Fix(#107): 모임 생성 시 쿠키에서 토큰을 못 받아오는 문제 해결

src/app/page.tsx, src/components/main/MainContentList.tsx, src/components/main/modals/LocationModal.tsx, src/lib/main/meetup.api.ts, src/utils/meetup.queryKey.ts
- `from`: feat/122/main-null
- 모임 찾기 페이지에서 모임이 없거나 검색 결과가 없을 때 사용자에게 알려줄 수 있도록 이미지를 추가했습니다.
- 추가로 쿼리키를 동일한 순서로 관리하기 위해서 유틸함수로 빼서 사용했습니다.
---|---
- close #122 
=> Refactor(#122): 모임 찾기 시 모임이 없다면 메시지 표시

src/components/create/CreateForm.tsx, src/components/create/FormSectionLeft.tsx, src/lib/main/meetup.api.ts
- `from`: fix/134/post-meetup
- 모임 생성 시 `formData` 의 `request`를 `Blob`을 사용해서 `application/json`으로 전송하니 문제가 해결되었습니다.
- 추가로 장소의 `value`가 잘못 설정 되어있는 부분도 수정했습니다.
- close #134 
=> Fix(#134): 모임 생성이 되지 않는 문제 해결

.github/workflows/SYNC_TO_DEPLOY_REPOSITORY.yml
- `from`: refactor/144/change-sync-ref
- workflow_run의 workflows를 정확한 파일 명으로 변경
- completed에 있었기에, 실패해도 trigger되는 문제를 막기 위해 if 조건문 추가
#144 
- 본인 username 제외하고 PR 날려주세요 
=> Fix(#144): workflow_run 정확한 파일 이름으로 변경

.github/workflows/SYNC_TO_DEPLOY_REPOSITORY.yml
- `from`: fix/144/change-sync-ref
- 파일명 => 워크플로우 name으로 변경
#144 
=> Fix(#144): 파일명이 아닌 workflow name으로 롤백

src/hooks/auths/useSignUp.ts
- `from`: fix/148/sign-up
#148 
=> Fix(#148): 회원가입 에러 로직 수정

src/app/(auth)/sign-up/page.tsx
- `from`: refactor/127/sign-up
- sign-in 과 마찬가지로 Spinner를 통한 UI 개선
#127 
=> Style(#127): 회원가입 요청 시 Spinner 이벤트 추가

src/store/auth/useUserStore.ts
- `from`: refactor/127/sign-in
- 이제 로그인 / 회원가입 시 즉각 유저의 정보가 반영됩니다. (새로고침을 해야 마이 페이지로 정상 이동하던 문제 해결)
#127 
=> Refactor(#127): useUserStore 로직 개선

src/app/layout.tsx, src/hooks/inputs/images/useLeavePage.ts
- `from`: feat/i162/clear-idb
- 페이지를 이동하게 되면 idb에 저장된 이미지가 삭제됩니다. (새로고침은 유지) 
#162 
=> Feat(#162): 페이지 이동시 idb에 저장된 이미지 삭제 추가

src/tests/dropdown.test.tsx, src/tests/modals/__snapshots__/modalController.test.tsx.snap, src/tests/modals/modalController.test.tsx, src/tests/popover.test.tsx
- `from`: feat/159/test-code
- modal, popover, dropdown 컴포넌트 테스트 코드 작성했습니다 
- `DeepSeek` 도움 받아서 작성했습니다 어렵네요...
- close #159
=> feat(#159): 공통 컴포넌트 테스트 코드 작성 ( modal, popover, dropdown )

src/components/common/nav-bar/NavBar.tsx
- `from`: fix/167/navBar-navigation
- 경로 수정
#167 
@ITHPARK @wjsdncl
=> Fix(#167): navBar 경로 수정

src/hooks/auths/useSignIn.ts
- `from`: refactor/127/useSignIn
- `useSingIn.ts` 에서 로그인 성공 시 토큰을 저장하는 로직을 제거하였습니다.
#127 
=> Refactor(#127): 로그인 토큰 저장 함수 제거

src/app/user/[id]/error.tsx, src/app/user/[id]/page.tsx, src/lib/user/getUserProfile.ts, src/tests/user-page/UserProfile.test.tsx, src/tests/user-page/error.test.tsx, src/tests/user/fetcher.test.ts, src/tests/user/getUserProfile.test.ts
- `from`: refactor/123/user-page
- 유저 프로필 컴포넌트 테스트 코드 작성
- API 호출 관련 테스트 코드 작성 (`fetcher`, `getUserProfile`)
- 에러 컴포넌트 테스트 코드 작성
- 에러 메세지 처리 로직 개선
- 백엔드 API 에러 해결 및 인증 전략 변경 반영 후 진행 예정 
- 인증 전략 변경(credentials: 'include') 반영 필요
- 백엔드 피드백 후 진행 예정
- #123 
=> Refactor(#123): 유저페이지 테스트 코드 작성 및 에러 처리 개선

src/hooks/auths/useSignOut.ts
- `from`: refactor/127/useSignOut
- token 삭제 훅을 제거합니다.
#127 
=> Refactor(#127): 로그아웃 훅 토큰 삭제 로직 제거

src/tests/buttons/ETCButton.test.tsx, src/tests/buttons/IconButton.test.tsx, src/tests/buttons/OutlineButton.test.tsx, src/tests/buttons/SolidButton.test.tsx
- `from`: feat/182/button
- 공통 버튼 컴포넌트에 대한 테스트 코드 작성
- #182 
=> Feat(#182): 공통 버튼 컴포넌트 테스트 코드 작성

src/hooks/auths/useSignIn.ts, src/middleware.ts
- `from`: refactor/178/middleware.ts
- 기존의 토큰 확인 로직 삭제
- API 요청을 통한 토큰 확인 로직 추가
#178 
아직 Merge하면 안됩니다.
(서버에서 API 구현 안됐음)
=> Refactor(#178): middleware.ts 토큰 검증 로직 개선

src/app/user/[id]/page.tsx, src/app/user/create_review/page.tsx, src/components/create-reaview/CreateReviewForm.tsx, src/components/user-page/MeetingList.tsx, src/components/user-page/UserTabs.tsx, src/hooks/review/useReviewMutation.ts, src/hooks/useInfiniteMeetings.ts, src/hooks/user/useEditProfile.ts, src/hooks/user/useProfile.ts, src/lib/review/reviewApi.ts, src/lib/user/fetcher.ts, src/lib/user/getUserProfile.ts, src/lib/user/userContent.ts, src/tests/user/fetcher.test.ts, src/tests/user/getUserProfile.test.ts, src/types/user-page/index.ts, src/utils/userPage.ts
- `from`: refactor/193/fetcher
- fetcher 인증 방식을 credentials로 변경
- 유저페이지, 리뷰작성 페이지 API 호출 로직 수정
- 프로필수정 페이지 API 호출 로직 수정
- #193 
=> Refactor(#193): fetcher 함수 리팩토링

src/app/(auth)/sign-in/basic/page.tsx, src/app/(auth)/sign-in/page.tsx, src/app/(auth)/sign-up/page.tsx, src/app/(auth)/sign-up/success/page.tsx, src/app/layout.tsx, src/app/page.tsx, src/app/wishlist/page.tsx, src/components/common/Header.tsx, src/components/common/layout/BackgroundWrapper.tsx, src/components/common/layout/HeaderWrapper.tsx, src/components/common/layout/NavBarWrapper.tsx, src/components/common/nav-bar/NavBar.tsx
- `from`: feat/198/navigation refactor
- `wrapper`를 이용하여 페이지마다 다르게 적용해줬습니다.
- 추가로 로그인/회원가입 페이지 CSS 수정했습니다.
메인(비로그인)|메인(로그인)
---|---
sign-in|basic
sign-up|create
- close #198 
=> Refactor(#198): 헤더, 하단 네비게이션, 배경을 페이지마다 다르게 설정

src/app/(auth)/sign-in/page.tsx
- `from`: refactor/127/sign-in
- 로그인 인트로 페이지 개선
#127 
=> Refactor(#127): 로그인 인트로 페이지 개선

src/app/user/edit_review/page.tsx, src/components/common/layout/HeaderWrapper.tsx, src/components/common/layout/NavBarWrapper.tsx, src/components/common/review/Review.tsx, src/components/common/review/ReviewContent.tsx, src/components/create-reaview/ReviewImageInput.tsx, src/components/edit-profile/EditProfileForm.tsx, src/components/edit-review/EditReviewForm.tsx, src/components/user/UserHeader.tsx, src/hooks/review/useReviewModals.ts, src/hooks/review/useReviewMutation.ts, src/lib/review/reviewApi.ts
- `from`: feat/172/edit-review
- 리뷰 수정페이지 생성
- 리뷰 조회 api 연결하여 기본값으로 설정
- 리뷰 수정 api 연결하여 수정 기능 구현
- 변경사항이 없을 때 모달 알림 처리
기존의 리뷰작성폼을 활용해보려고 했는데, 종료일까지 시간이 없어서 일단 개별 작업으로 구현했습니다🥹
응답에 리뷰이미지가 없어서 일단 이미지 부분은 제외하고 구현했습니다.
https://github.com/user-attachments/assets/422499fb-0870-4bff-a60c-dd6185ea6f08
https://github.com/user-attachments/assets/ace29f8d-0022-419b-9085-8a2562f425f4
=> Feat(#172): 리뷰수정 페이지

src/app/layout.tsx, src/app/user/edit_profile/page.tsx, src/components/common/Dropdown.tsx, src/components/common/Header.tsx, src/components/common/nav-bar/NavBar.tsx, src/components/edit-profile/ContactBanner.tsx, src/components/edit-profile/EditProfileForm.tsx, src/components/user/UserHeader.tsx, src/hooks/auths/useSignOut.ts, src/hooks/user/useEditProfile.ts, src/tests/edit-profile/ContactBanner.test.tsx, src/types/dropdown.type.ts
- `from`: refactor/132/edit-profile
- 폰트 preload 설정
- ContactBanner UI 세부사항 개선
- 프로필 이미지 변경 후 상태 관리 스토어 업데이트 로직 추가
- EditProfileForm의 controlled input 관련 에러 해결
- UserHeader 하이드레이션 에러 해결
- 헤더에 로그아웃 연결
https://github.com/user-attachments/assets/e7300db5-4ca4-4b0e-bf39-816ea06e1627
- #132 
=> Refactor(#132): 프로필 수정 페이지 종합 개선

src/components/common/inputs/ImageUpload.tsx
- `from`: fix/222/deleteImage
- 이미 이미지가 있는 경우, 이미지가 삭제되게 수정했습니다.
#222 
=> Fix(#222): 이미지 삭제 에러 해결

src/components/common/review/Review.tsx, src/components/common/review/ReviewContent.tsx, src/components/create-reaview/CreateReviewForm.tsx, src/components/edit-review/EditReviewForm.tsx, src/types/review.ts, src/types/user-page/index.ts, src/utils/userContentMapper.ts, src/utils/userPage.ts
- `from`: bug/230/review-rating
- 리뷰 수정 시 옵셔널 요청이 불가능한 문제 해결
- 평점을 변경하지 않았는데 1점으로 바뀌는 문제 해결
- 수정폼에 기존 이미지 보여주
- 리뷰 작성 시 이미지 요청 방식 변경
- 리뷰카드 컴포넌트에 리뷰이미지 추가
- 내가 작성한 리뷰내용 클릭시 높낮이 토글되도록 변경 (기존 모임상세로 이동은 제거)
- 리뷰카드 유저이미지에 Image 태그 적용
https://github.com/user-attachments/assets/c14a517b-1bc9-4854-980e-e557cbf3071e
https://github.com/user-attachments/assets/e0ad341f-d8a3-4963-926c-0a7607eb1f9f
- #230 
=> Bug(#230): 리뷰 관련 이슈 해결

src/app/wishlist/page.tsx
- `from`: feat/231/wishlist
- 페이지 양 옆에 padding값을 추가하였습니다
.png…]()
- #231 
@joshuayeyo @wjsdncl @Stilllee
=> Feat(#231): 찜한 모임 페이지 padding값추가

src/hooks/auths/useSignIn.ts
- `from`: fix/234/sign-up
- setUser를 redirect가 `false`인 경우에도 실행되게 변경
#234 
=> Fix(#234): Modify setUser 함수를 언제나 실행되게 변경
